version: '2.4'
services:
  openhpc-common:
    image: ${REGISTRY}/vcp/openhpc:common-${TAG}
    build: ./common
  openhpc-master:
    image: ${REGISTRY}/vcp/openhpc:master-${TAG}
    build:
     context: ./master
     args:
     - TAG=$TAG
     - REGISTRY=$REGISTRY
  openhpc-compute:
    image: ${REGISTRY}/vcp/openhpc:compute-${TAG}
    build:
     context: ./compute
     args:
     - TAG=$TAG
     - REGISTRY=$REGISTRY
