---
- name: postgres data directory
  file:
    path: "{{postgres_dir}}/data"
    state: directory

- name: postgres init files directory
  file:
    path: "{{postgres_dir}}/init"
    state: directory

- name: deploy init.sql
  copy:
    src: init.sql
    dest: "{{postgres_dir}}/init/"
