- name: pull image
  command: "docker pull {{jupyterhub_image}}"
- file:
    path: "{{base_dir}}"
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  become: true
- name: deploy logo.png
  get_url:
    url: "{{logo_url}}"
    dest: "{{base_dir}}/logo.png"
